spring:
  application:
    name: fanta-f1-app-backend
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${FANTAF1_AUTH_ISSUER_URI}

logging:
  level:
    root: info

jolpica:
  base-url: https://api.jolpi.ca/ergast/f1/

open-f1:
  base-url: https://api.openf1.org
  api-version: v1

notifications:
  lineup:
    close-reminder-time-before: 12h